website/auth.py
from distutils.log import error
from nis import cat
from flask import Blueprint, render_template, request, flash, redirect, session, url_for
from .models import Students
from . import db
from passlib.hash import pbkdf2_sha256 as hasher # type: ignore
from functools import wraps


auth = Blueprint('auth', __name__)

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'id' in session:
            return f(*args, **kwargs)
        else:
            return redirect("/")
    return wrap
	
#DONEEEEEEEEEE	
@auth.route('/', methods=['GET','POST'])
def login():
    if request.method == "GET":
        return render_template("login.html")
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        student = Students.query.filter_by(email = email).first()
        if student:
            if hasher.verify(password, student.password):
                session["id"] = student.id
                return redirect(url_for('views.home', index=0))
            else:
                flash("Your password is incorrect!", category='error')
        else:
            flash("User not found, try creating an account first!", category='error')
    return render_template("login.html")
    

@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "GET":
        return render_template("signup.html")
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        password = request.form["password"]
        password2 = request.form["password2"]
        if password != password2:
            flash("The passwords don't match!", category='error')
            return render_template("sign_up.html")
        # before the line of code below was "elif "student.aisb.hu" not in email or "aisb.hu" not in email:", but the first half of the or is redundant since "aisb.hu" is in "student.aisb.hu"
        elif "aisb.hu" not in email:
            flash("Your email doesn't belong to this organization!", category='error')
            return render_template("sign_up.html")
        elif name == None or email == None or password == None or password2 == None:
            flash("Please fill out all fields!", category='error')
            return render_template("sign_up.html")
        else:
            hash = hasher.hash(password)
            student = Students(email=email, name=name, password=hash)
            db.session.add(student)
            db.session.commit()
            session["id"] = student.id
            flash("Account successfully created")
            return redirect(url_for('views.home', index=0))
    return render_template("signup.html")

website/views.py
from flask import Blueprint, Flask, redirect, render_template, request, session, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc
from .models import *
from passlib.hash import pbkdf2_sha256 as hasher
from os import path
from functools import wraps
from website.models import *
from . import db


views = Blueprint('views', __name__)

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'id' in session:
            return f(*args, **kwargs)
        else:
            return redirect("/")
    return wrap


@views.route("/home/<index>", methods = ["GET", "POST"])
@login_required
def home(index):
    student = Students.query.filter_by(id=session['id']).first()
    books = Books.query.filter_by(student_id = session["id"], status="reading").order_by(desc(Books.book_id)).all()
    
    if request.method == 'POST':
        index = request.form["next_book"]
        if int(index) >= len(books):
            index = 0
   
    return render_template("home.html", student=student, books=books, index=index)


@views.route("/list", methods = ["GET", "POST"])
@login_required
def list():
    student = Students.query.filter_by(id=session['id']).first()
    books = Books.query.filter_by(student_id = session["id"]).order_by(Books.status).all()
    if request.method=='POST' and request.form['button'][:4] == "more":
        return redirect(url_for('views.detail', book_id=request.form['button'][4:]))
    return render_template("list.html", student=student, books=books)


@views.route("/add", methods = ["GET", "POST"])
@login_required
def add():
    if request.method == "GET":
        return render_template("add.html")
    else:
        name = request.form["name"]
        author = request.form["author"]
        total_pages = (request.form["no_pages"])
        current_page = (request.form["current_page"])
        
        f = request.files['file']
        try:
            f.save("davids-ia/website/static/images/" + name.replace(" ", "_"))
        except:
            f.filename = "batman.png"
        book = Books(student_id = session["id"], name = name, author = author, pages = total_pages, bookcover = "davids-ia/website/static/images/" + str(f.filename), currentpage = current_page, status="reading")
        db.session.add(book)
        db.session.commit()
        flash("Book successfully added!")
        
        return redirect(url_for('views.list'))
    
    
@views.route("/goal", methods = ["GET", "POST"])
@login_required
def goal():
    if request.method == "GET":
        goals = Goals.query.filter_by(student_id=session["id"])
        goal_array = []
        for i in goals:
            goal_array.append(i)
        return render_template("goal.html", goals=goal_array)
    else:
        value = request.form["button"]
    
    #Save
        if value == "save":
            new_goal = Goals(student_id=session["id"], goal=request.form.get("title"), checked=False)
            db.session.add(new_goal)
            db.session.commit()
    #Delete
        elif value[:3] == "del":
            deleted = Goals.query.filter_by(id=value[3:]).first()
            db.session.delete(deleted)
            db.session.commit()
    #Checkbox
        else:
            goal = Goals.query.get(value[5:])
            if goal:
                goal.checked = not goal.checked
                db.session.add(goal)
                db.session.commit()
            
        return redirect("/goal")
    
@views.route("/detail/<book_id>", methods=["GET", "POST"])
@login_required
def detail(book_id):
    if request.method=='POST': book_id = request.form['button']
    book = Books.query.filter_by(book_id=book_id).first()
    if not book:
        flash("Book not found", category="error")
    elif request.method == 'POST':
        print("ID" + str(book_id))
        name=book.name
        author=book.author
        pages=book.pages
        current_page=book.currentpage
        file_name=book.bookcover
        status = request.form['book_status']
        
        if request.form['name'] != "": name = request.form["name"]
        if request.form['author'] != "": author = request.form["author"]
        if request.form['no_pages'] != "": pages = (request.form["no_pages"])
        if request.form['current_page'] != "": current_page = (request.form["current_page"])
        if request.files['file']: file_name="davids-ia/website/static/images/static" + str(request.files['file'].name)
        flash(str(request.files['file'].name))
        
        new_book = Books(student_id = session["id"], name = name, author = author, pages = pages, bookcover = file_name, currentpage = current_page, status=status)
        db.session.add(new_book)
        db.session.delete(book)
        db.session.commit()
        flash("Book successfully added!")
        
        return redirect(url_for('views.list'))
    
    return render_template("detail.html", book=book)
        
@views.route("/challenge", methods=["GET", "POST"])
@login_required
def challenge():
    challenges = Challenges.query.all()
    return render_template("challenge.html", challenges=challenges)

website/templates/add.html
{% extends "base.html" %} 
{% block title %}New Book{% endblock %}



{% block content %}

<form method="POST" action = "./add" class = "form" enctype="multipart/form-data">
<div class="container px-5 py-5">
    <div class="row">
      <div class="col-sm-6" style="height:500px;" >
        <span class="align-middle px-5 py-5" style="width:400px" align="center">
            <div class="upload">
                <div class="picture">
                    <img src = "static/images/book_cover.png" id = "image">
                </div>
                <label for = "file" class = "label">Upload Image</label>
                <input style = "display: none;" type="file" id="file" accept = "/image" onchange="showPreview(event)" name = "file">
            </div>
        </span>
      </div>
      <div class="col-sm-6">
        
        <form class = "form" action = "./signup" method = "POST">
            <br>
            <h1 align="center">New Book</h1>
            <br>
            <div id = "big_gap" align="center">
                <img src="static/images/book_stack.png">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Title" name = "name" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Author" name = "author" required>
            </div>
            <div class="form-group">
                <input type="number" class="form-control" placeholder="Number of pages" name = "no_pages" required>
            </div>
            <div class="form-group">
                <input type="number" class="form-control" placeholder="Current Page" name = "current_page" required>
            </div>
            <div class="form-group" align="right">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>        


      </div>
    </div>
</div>
</form>

<script>
    function showPreview(event) {
         if (event.target.files.length > 0) {
             var source = URL.createObjectURL(event.target.files[0]);
             var preview = document.getElementById("image");
             preview.src = source
             preview.style.display = "block";
         }
    }
</script>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
    <style>
        body {
        background-color: rgb(218, 226, 241);
        }

        h1 { font-family: "Didot"; font-size: 40px; font-style: normal; font-variant: normal; font-weight: 700; line-height: 26.4px; } h3 { font-family: "Playfair Display"; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 700; line-height: 15.4px; } p { font-family: "Playfair Display"; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; line-height: 20px; } blockquote { font-family: "Playfair Display"; font-size: 21px; font-style: normal; font-variant: normal; font-weight: 400; line-height: 30px; } pre { font-family: "Playfair Display"; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; line-height: 18.5714px; }
        {% block add_style %}{% endblock%}
      </style>

  </head>

  <body>


  {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/challenge.html
{% extends "base.html" %} {% block title %}Challenges{% endblock %}
{% block content %}

<br>
<br>

<div style="display:flex; flex-direction: row; justify-content: center; align-items: center]">

  <ul class="list-group list-group-flush" style="background-color: rgb(218, 226, 241);">

    {% for challenge in challenges %}
    <form method='POST'>
    <li class="list-group-item">

        <div class="p-2">
          <div class="d-flex justify-content-center">
            
            <div class="d-flex justify-content-between">
              <div class="p-2" style="width: 200px">{{ challenge.name | truncate(22) }}</div>
              <img src = "{{ challenge.badge }}" id = "image" >
              <div style="width:20px"></div>
            </div>
        </div>
    </li>
    </form>
    {% endfor %}

  </ul>

</div>

{% endblock %}

website/templates/detail.html
{% extends "base.html" %} {% block title %}Detail View{% endblock %}
{% block content %}


<form method="POST" action = "./add" class = "form" enctype="multipart/form-data">
    <div class="container px-5 py-5">
        <div class="row">
          <div class="col-sm-6" style="height:500px;" >
            <span class="align-middle px-5 py-5" align="center">
                    <div  style="padding: 10px; width: 30vw; height: 60vh;">
                        
                        <img src = "{{ book.bookcover }}" id = "image" alt="{{ book.bookcover }}" style="padding: 10px; width: 30vw; height: 60vh;">
                         
                    </div>
                    
                    <label for = "file" class = "label">Upload New Image</label>
                    <input style = "display: none;" type="file" id="file" accept = "/image" onchange="showPreview(event)" name = "file">
    
            </span>
          </div>
          <div class="col-sm-6">
            
            <form class = "form" action = "./signup" method = "POST">
                <br>
                <h1 align="center">Edit Book</h1>
                <br>
                <div id = "big_gap" align="center">
                    <img src="static/images/book_stack.png">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="{{book.name}}" name = "name" >
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="{{book.author}}" name = "author" >
                </div>
                <div class="form-group">
                    <input type="number" class="form-control" placeholder="{{book.pages}}" name = "no_pages" >
                </div>
                <div class="form-group">
                    <input type="number" class="form-control" placeholder="{{book.currentpage}}" name = "current_page" >
                </div>
                {{book.status}}
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary {% if book.status|string == "Status.reading" %} active{% endif %}">
                        <input type="radio" name="book_status" id="reading" value="reading" autocomplete="off">Reading</label>
                    <label class="btn btn-secondary {% if book.status|string == "Status.finished" %} active{% endif %}">
                        <input type="radio" name="book_status" id="reading" value="finished" autocomplete="off">Finished</label>
                    <label class="btn btn-secondary {% if book.status|string == "Status.waiting" %} active{% endif %}">
                        <input type="radio" name="book_status" id="waiting" value="waiting" autocomplete="off" >Waiting</label>
                    <label class="btn btn-secondary {% if book.status|string == "Status.skimmed" %} active{% endif %}">
                        <input type="radio" name="book_status" id="skimmed" value="skimmed" autocomplete="off">Skimmed</label>
                    <label class="btn btn-secondary {% if book.status|string == "Status.dnf" %} active{% endif %}">
                        <input type="radio" name="book_status" id="dnf" value="dnf" autocomplete="off">Dnf</label>
                </div>
                <br>
                <div class="form-group" align="right">
                    <button name="button" class="btn btn-primary" value={{book.book_id}}> Submit</button>
                </div>
            </form>        
    
    
          </div>
        </div>
    </div>
    </form>
    
    <script>
        function showPreview(event) {
             if (event.target.files.length > 0) {
                 var source = URL.createObjectURL(event.target.files[0]);
                 var preview = document.getElementById("image");
                 preview.src = source
                 preview.style.display = "block";
             }
        }
    </script>

{% endblock %}

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book Page</title>
</head>
<style>
    .background {
        width: 88%;
        transform: translate(7%, 0);
        position: relative;
    }

    .management {
        top: 10%;
        left: 10%;
        display: inline-block;
        position: absolute;
        width: 50vw;
        cursor: pointer;
    }
    .all {
        width: 15vw;
        position: absolute;
        z-index: 100;
        margin-left: 47%;
    }

    .cover {
        width: 15vw;
        position: absolute;
        z-index: 100;
        height: 33vh;
        transform: translate(2vw, -2vh);
    }
    .text {
        position: absolute;
        z-index: 100;
        font-size: 2.4vw;
        font-weight: bold;
        transform: translate(18%, 150%);
        text-decoration: none;
        color: black;
    }
    .goals {
        top: 40%;
        left: 10%;
        display: inline-block;
        position: absolute;
        width: 50vw;
        cursor: pointer;
    }
    #more {
        transform: translate(50%, 100%) !important;
    }
    .challenges {
        top: 70%;
        left: 10%;
        display: inline-block;
        position: absolute;
        width: 50vw;
        cursor: pointer;
    }
    .form {
        width: 88%;
        height: 100%;
        z-index: 120;
    }
    .profile {
        right: 14%;
        top: 5%;
        position: absolute;
        background-color: rgb(140, 196, 245);
        border-radius: 15px;
        padding-left: 0.5vw;
        padding-right: 0.5vw;
        height: 9vh;
        cursor: pointer;
        width: 15vw;
    }

    .small_text {
        transform: translate(0vw, -1.5vh);
        text-align: left;
    }
    .title {
        font-size: 1.3rem;
        text-align: center !important;
        font-weight: bold;
    }
    
    .logout {
        right: 35%;
        top: 5%;
        color: white;
        background-color: red;
        border-radius: 20px;
        position: absolute;
        width: 12vw;
        height: 4vh;
        padding: 1vw;
    }

    .reading {
        right: 23%;
        top: 15%;
        position: absolute;
        font-size: 2vw;
        transform: translate(0, 2vh);
    }

    .cover {
        top: 23%;
        right: 32%;
        width: 15vw;
        position: absolute;
        display: inline-block;
    }

    .right {
        transform: translate(15vw,5vh);
        font-size: 1.2vw;
        font-weight: bold;
    }

    .status {
        border-radius: 15px;
        border: 2px solid green;
        padding: 1vw;
        transform: translate(1vw, 0vh);
        cursor: pointer;
        text-decoration: none;
        transform: translate(0, -3vh);
    }

    #down {
        top: 55% !important;
    }
    .badges {
        display: inline-block;
        transform: translate(0, 0.1vh);
    }
    .stats {
        top: 66%;
        right: 15%;
        position: absolute;
        font-size: 1.2vw;
        font-weight: bold;
    }
    .badge {
        width: 3vw;
        top: 85%;
    }
    .push {
        margin-bottom: 3vw;
    }
</style>
<body>
    <img src="static/images/book_background.png" alt="I like bananas" class="background">

    <form class = "form" method = "POST" action = "./book">
        <a href = "{{url_for('views.list')}}">
            <div class="management">
                <p class = "text"> Book Management</p>
                <img src="static/images/a.png" alt="" class="all">
            </div>
        </a>
    
        <a href = "{{url_for('views.goal')}}">
            <div class="goals">
                <p class = "text" id = "more"> Goal Tracker </p>
                <img src="static/images/b.png" alt="" class="all">
            </div>
        </a>
    
        <a href = "/challenges">
            <div class="challenges">
                <p class = "text" id = "less"> Reading Challenges </p>
                <img src="static/images/c.png" alt="" class="all">
            </div>
        </a>

        <a>
            <div class="profile">
                <p class = "small_text"> Email: {{student.email}} </p>
                <p class = "small_text"> Name: {{student.name}} </p>
            </div>
        </a>
        <form method = "POST" action = "/book">
            <button type = "submit" name = "logout" value = "logout">
                <div class="logout">
                    <p style = "font-size: 1.25rem; font-weight: bold; transform: translate(0, -2vh);"> Logout </p>
                </div>
            </button>
        </form>

        
            <h3 class = "reading">Currently Reading</h3>
            <div class="cover">
                {% if books|length > 0 %}
                <img src = " {{ books[index|int].cover }}" class = "cover">
                <div class = "right">
                    <p>Name: {{books[index|int].title}}</p>
                    <p>Author: {{books[index|int].author}}</p>
                    <p>Total Page Number: {{books[index|int].pages}}</p>
                    <p class = "push">Current Page: {{books[index|int].currentpage}}</p>
                    <form method = "POST">
                        <button name = "next_book" value = "{{ (index|int) + 1 }}" class = "status">Next Book</button>
                    </form>
                </div>
               
                {% endif %}
            </div>
            <h3 class = "reading" id="down">Current Statistics</h3>
            <div class="stats">
                <p>Number of Books Read: {{read}}</p>
                <p>Number of Books Planning to Read: {{plan}}</p>
                <p>Upcoming Reads: {{ bookname }}</p>
                <p>Badges: </p>
                <div class = "badges">
                    <img src="/static/images/spiderman.jpg" class = "badge"> <img src="/static/images/spiderman.jpg" class = "badge"> <img src="/static/images/spiderman.jpg" class = "badge"> <img src="/static/images/circle.jpg" class = "badge">                <img src="static/images/circle.png" class = "badge"> <img src="static/images/circle.png" class = "badge"> <img src="static/images/circle.png" class = "badge"> <img src="static/images/circle.png" class = "badge"> <img src="static/images/circle.png" class = "badge"> <img src="static/images/circle.png" class = "badge">
                </div>
            </div>
        
    </form>
</body>
</html>

website/templates/list.html
{% extends "base.html" %} {% block title %}Classes{% endblock %}
{% block content %}

<br>

<br>

<div style="display:flex; flex-direction: row; justify-content: center; align-items: center]">

  <ul class="list-group list-group-flush" style="background-color: rgb(218, 226, 241);">

    {% for book in books %}
    <form method='POST'>
    <li class="list-group-item">

        <div class="p-2">
          <div class="d-flex justify-content-center">
            
            <div class="d-flex justify-content-between">
              <div class="p-2" style="width: 200px">{{ book.name | truncate(22) }}</div>
                
                
                  <div class="p-2">
                    {% if book.status|string == "Status.reading" %}
                    <button name="button" class="btn btn-primary" value="more{{ book.book_id }}">More</button>
                    {% else %}
                    <button name="button" class="btn btn-danger" value="more{{ book.book_id }}">More</button>
                    {% endif %}
                  </div>
                
              <div style="width:20px"></div>
            </div>
        </div>
    </li>
</form>
  {% endfor %}

  </ul>

  

</div>

<div class="mt-5">
    <a href = "{{url_for('views.add')}}">
        <btn class="btn btn-primary">Add</btn>
    </a>
  </div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock%}

{% block content %}
<p>HEre is sum text</p>

<div class="form-group">
<form method = "POST">
    <br />
    <h1 align="center">Login</h1>
    <br>
    <div class="form-group" align="center">
        <img src="static/images/book.png" >
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Email" name = "email" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name = "password" required>
    </div>
    <br>
    
    <div class="form-group" align="right">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <br>
    <br>
    <div class="form-group" align="center">
        <a href="{{url_for('auth.signup')}}" class = "link">Don't have an account? Sign-up</a>
    </div>
</form>



</div>

{% endblock %}

website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<form class = "form" action = "./signup" method = "POST">
    <br>
    <h1 align="center">Sign Up</h1>
    <br>
    <div id = "big_gap" align="center">
        <img src="static/images/book_stack.png">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Email" name = "email" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Name" name = "name" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name = "password" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Re-Enter Password" name = "password2" required>
    </div>
    <div class="form-group" align="right">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <a href="{{url_for('auth.login')}}" class = "link">Already have an account? Login</a>
</form>

{% endblock %}